name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

  android-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java for Android SDK tools
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          api-level: 29
          build-tools: 29.0.3

      - name: Set up Java for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
        working-directory: android

      - name: Run unit tests
        env:
          JAVA_TOOL_OPTIONS: -Xmx2g
        run: ./gradlew test --stacktrace
        working-directory: android

  ios-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build and test
        run: |
          xcodebuild \
            -project ios/RNCookieManagerIOS.xcodeproj \
            -scheme RNCookieManagerIOS \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' \
            test \
            CODE_SIGNING_ALLOWED=NO

